#editor = "neovim"

[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true

[preview]
image_filter = "lanczos3"
image_quality = 90
tab_size = 1
max_width = 600
max_height = 900
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[theme]
background = "0x282c34"
foreground = "0xc5c8c6"
black = "0x282c34"
red = "0xcc6666"
green = "0xb5bd68"
yellow = "0xf0c674"
blue = "0x81a2be"
magenta = "0xb294bb"
cyan = "0x8abeb7"
white = "0xc5c8c6"
bright_black = "0x969896"
bright_red = "0xcc6666"
bright_green = "0xb5bd68"
bright_yellow = "0xf0c674"
bright_blue = "0x81a2be"
bright_magenta = "0xb294bb"
bright_cyan = "0x8abeb7"
bright_white = "0xffffff"
