[font]

normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"

[cursor]
style = "Block"

[window]
opacity = 0.8
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "full"
startup_mode = "Windowed"
resize_increments = true

[colors]
# Nordic theme
primary.background = '0x2E3440'
primary.foreground = '0xD8DEE9'

normal.black = '0x3B4252'
normal.red = '0xBF616A'
normal.green = '0xA3BE8C'
normal.yellow = '0xEBCB8B'
normal.blue = '0x81A1C1'
normal.magenta = '0xB48EAD'
normal.cyan = '0x88C0D0'
normal.white = '0xE5E9F0'

bright.black = '0x4C566A'
bright.red = '0xBF616A'
bright.green = '0xA3BE8C'
bright.yellow = '0xEBCB8B'
bright.blue = '0x81A1C1'
bright.magenta = '0xB48EAD'
bright.cyan = '0x8FBCBB'
bright.white = '0xECEFF4'


[selection]
semantic_escape_chars = " ,│`|:\"'()[]{}<>"
